

<ImageCard>:
    orientation: 'vertical'
    size_hint_y: None
    height: self.width
    padding: dp(20)

    canvas.before:
        Color:
            rgba: (1, 1, 1, .15) if self.is_selected else (0, 0, 0, 0)
        Rectangle:
            pos: (self.pos[0] + 2, self.pos[1] + 2)
            size: (self.size[0] - 4, self.size[1] - 4)
        Color:
            rgba: (0.6, 0.75, 0.75, 1) if self.is_active else (0, 0, 0, 0)
        Line:
            width: 2.
            rectangle: (self.x, self.y, self.width, self.height)

    ClickableImage:
        source: root.thumb_source
        fit_mode: "contain"
        size_hint_y: 0.8
        on_single_click: root._on_single_click(args[1])
        on_double_click: root._on_double_click(args[1])