<ThumbnailBrowserScreen>:
    name: 'browser'
    FloatLayout:
        Label:
            id: images_empty_label
            pos: self.pos
            size_hint: (1, 1)
            opacity: 1 if len(app.image_list) == 0 else 0
            text: "Drop images or directory here to add to the catalog."
            font_size: '24sp'
            color: (0.7, 0.7, 0.7, 1)
            pos: self.pos
            height: 100
            halign: 'center'
            valign: 'middle'
            text_size: self.size

        BoxLayout:
            id: grid_box
            pos: self.pos
            size_hint: (1, 1)
            opacity: 1
            height: 100
            ScrollView:
                id: scroll_area
                do_scroll_x: False
                do_scroll_y: True

                GridLayout:
                    id: thumbnail_grid
                    cols: root.columns
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: dp(2)
                    padding: dp(40)


<ImagePreviewScreen>:
    name: 'preview'

    BoxLayout:
        id: preview_box
        orientation: 'vertical'
        spacing: dp(25)
        padding: dp(50)