<FileToggle>:
  text_size: self.size
  halign: "left"
  valign: "center"
  size_hint_y: None
  height: "48sp"
  padding: "10sp"
  group: root.hash
  text: root.url

<ImportScreen>:
  name: "import"

  GridLayout:
    cols: 1
    padding: dp(20)

    Label:
      text: "Import images"
      text_size: self.size
      halign: 'left'
      valign: 'top'
      font_size: "48sp"
      size_hint_y: None
      height: "60sp"

    GridLayout:
      id: import_duplicates
      cols: 1
      padding: dp(20)

      Label:
        text: "Import duplicates"
        text_size: self.size
        halign: 'left'
        valign: 'top'
        font_size: "24sp"
        size_hint_y: None
        height: "60sp"

      GridLayout:
        id: import_duplicates_list
        cols: 1
        padding: dp(20)
        spacing: "10sp"

        BoxLayout:
          orientation: "horizontal"
          spacing: "10sp"
          padding: 0

          FloatLayout:
            size_hint_x: 0.2
            size_hint_y: 1
            height: self.width

            Image:
              fit_mode: "contain"
              size_hint: (1, 1)
              pos_hint: {"center_x": 0.5, "center_y": 0.5}
              source: "/Users/kpegan/Desktop/Level_0/Level_1A/Level_2/46263009845_f00f4dc22c_o.jpg"

          GridLayout:
            cols: 1

            FileToggle:
              hash: "asd;lfkjasd;flkajsdf"
              url: "/Users/kpegan/Desktop/Level_0/Level_1A/Level_2/46263009845_f00f4dc22c_o.jpg"

            FileToggle:
              hash: "asd;lfkjasd;flkajsdf"
              url: "/Users/kpegan/Desktop/Level_0/Level_1B/46114644295_18eef4b685_o.jpg"

            FileToggle:
              hash: "asd;lfkjasd;flkajsdf"
              url: "/Users/kpegan/Desktop/Level_0/39737483343_97c4be7232_o.jpg"

            FileToggle:
              hash: "asd;lfkjasd;flkajsdf"
              url: "/Users/kpegan/Desktop/Level_0/Level_1A/Level_2/46263009845_f00f4dc22c_o.jpg"

            FileToggle:
              hash: "asd;lfkjasd;flkajsdf"
              url: "/Users/kpegan/Desktop/Level_0/Level_1B/46114644295_18eef4b685_o.jpg"

            FileToggle:
              hash: "asd;lfkjasd;flkajsdf"
              url: "/Users/kpegan/Desktop/Level_0/39737483343_97c4be7232_o.jpg"


    GridLayout:
      id: catalog_duplicates
      cols: 1
      padding: dp(20)

      Label:
        text: "Catalog duplicates"
        text_size: self.size
        halign: 'left'
        valign: 'top'
        font_size: "24sp"
        size_hint_y: None
        height: "60sp"

    BoxLayout:
      id: submit_buttons
      orientation: 'horizontal'
      size_hint_y: 0.15
      spacing: "10sp"

      Button:
        text: "Cancel"

      Button:
        text: "Import"


  