<ImportScreen>:
  name: "import"

  BoxLayout:
    orientation: "vertical"
    spacing: dp(25)
    padding: dp(50)

    Label:
      text: "Import things man"
      text_size: self.size
      halign: 'left'
      valign: 'top'

    BoxLayout:
      id: import_duplicates
      orientation: "vertical"
      spacing: dp(10)
      padding: dp(5)

    Label:
      text:"Dupes in the ports"
      text_size: self.size
      halign: 'left'
      valign: 'top'
    
    BoxLayout:
      id: catalog_duplicates
      orientation: "vertical"
      spacing: dp(10)
      padding: dp(5)

      Label:
        text: "Duplicate images in catalog:"
        text_size: self.size
        halign: 'left'
        valign: 'top'

    BoxLayout:
      orientation: "horizontal"
      size_hint_y: 0.2
      spacing: dp(10)

      Button:
        text: "Cancel"
        on_release: app.view_thumbnail_browser()
      Button:
        text: "Import images"
