# ui/main_screen.kv
<MainScreen>:
    BoxLayout:
        orientation: 'vertical'
        ScrollView:
            GridLayout:
                id: image_grid
                cols: 4
                size_hint_y: None
                height: self.minimum_height
                row_default_height: 200
                row_force_default: True
                spacing: 10
                padding: 10
            
